*Adapted from: https://keras.io/examples/vision/mnist_convnet/*

# Setup

In [63]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow.keras as keras

# in keras you can define layers
from tensorflow.keras import layers
# print(keras.__version__)
keras.backend.backend()

'tensorflow'

In [64]:
!pip install pandas
import pandas as pd

# Load the data

In [74]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# in numpy everything needs to be of the same type to be put into an array
raw_labels = np.genfromtxt("C:\\Users\\mccal\\Documents\\CCI\\Coding Five\\bsc-coding-five\\perceptron\\Fish.csv", dtype="str", delimiter=",", skip_header=1, usecols=(0))
print(raw_labels)

raw_data = np.genfromtxt("C:\\Users\\mccal\\Documents\\CCI\\Coding Five\\bsc-coding-five\\perceptron\\Fish.csv", delimiter=",", skip_header=1, usecols=(1,2,3,4,5,6))
print(raw_data)

['Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream'
 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Bream' 'Roach'
 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach' 'Roach'
 'Roach' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish' 'Whitefish'
 'Whitefish' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki'
 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Parkki' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'
 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch' 'Perch'

# Display the data

In [66]:
# plt.clf()
# for i in range(9):
#     ax = plt.subplot(3, 3, i + 1)
#     plt.imshow(x_train[i], cmap='gray')
#     plt.title(y_train[i])
#     plt.axis("off")

# plt.show()

# Prepare the data

In this instance we keep the original shape of the data (ie. 28x28) as it can be flatten by Keras later.

In [75]:
# Scale images to the [0, 1] range
# x_train = x_train.astype("float32") / 255
# x_test = x_test.astype("float32") / 255
# # Make sure images have shape (28, 28, 1)
# x_train = np.expand_dims(x_train, -1)
# x_test = np.expand_dims(x_test, -1)
# print("x_train shape:", x_train.shape)
# print(x_train.shape[0], "train samples")
# print(x_test.shape[0], "test samples")

# Model / data parameters
# num_classes = 10
# input_shape = x_train.shape[1:]

# convert class vectors to binary class matrices
# y_train = keras.utils.to_categorical(y_train, num_classes)
# y_test = keras.utils.to_categorical(y_test, num_classes)

x_train = raw_data
y_train = raw_labels
# to_categorical need integers to convert a class vector into a binary class matrix
# y_train = keras.utils.to_categorical(raw_labels, 7, dtype="int")

print(x_train)
print(y_train)

[[2.42000e+02 2.32000e+01 2.54000e+01 3.00000e+01 1.15200e+01 4.02000e+00]
 [2.90000e+02 2.40000e+01 2.63000e+01 3.12000e+01 1.24800e+01 4.30560e+00]
 [3.40000e+02 2.39000e+01 2.65000e+01 3.11000e+01 1.23778e+01 4.69610e+00]
 [3.63000e+02 2.63000e+01 2.90000e+01 3.35000e+01 1.27300e+01 4.45550e+00]
 [4.30000e+02 2.65000e+01 2.90000e+01 3.40000e+01 1.24440e+01 5.13400e+00]
 [4.50000e+02 2.68000e+01 2.97000e+01 3.47000e+01 1.36024e+01 4.92740e+00]
 [5.00000e+02 2.68000e+01 2.97000e+01 3.45000e+01 1.41795e+01 5.27850e+00]
 [3.90000e+02 2.76000e+01 3.00000e+01 3.50000e+01 1.26700e+01 4.69000e+00]
 [4.50000e+02 2.76000e+01 3.00000e+01 3.51000e+01 1.40049e+01 4.84380e+00]
 [5.00000e+02 2.85000e+01 3.07000e+01 3.62000e+01 1.42266e+01 4.95940e+00]
 [4.75000e+02 2.84000e+01 3.10000e+01 3.62000e+01 1.42628e+01 5.10420e+00]
 [5.00000e+02 2.87000e+01 3.10000e+01 3.62000e+01 1.43714e+01 4.81460e+00]
 [5.00000e+02 2.91000e+01 3.15000e+01 3.64000e+01 1.37592e+01 4.36800e+00]
 [3.40000e+02 2.95000e+01

# Build the model

We have the usual input and output layer plus just after the input layer we have a flatten layer to make sure the data passed to our network is 1D. Next we have three fully connected hidden layers of various size but all uses the ReLU activation function. The final activation of the output layer is the Softmax function.

In [76]:
vocab = ["Bream", "Roach", "Whitefish", "Parkki", "Perch", "Pike", "Smelt"]
model = keras.Sequential(
    [
        layers.InputLayer(input_shape=(6)),
        # layers.Flatten(),
        layers.Dense(10, activation="relu"),
        # layers.Dense(64, activation="relu"),
        # layers.Dense(48, activation="relu"),
        layers.Dense(7, activation="sigmoid"),
    ]
)

model.summary()

Model: "sequential_21"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_42 (Dense)            (None, 10)                70        
                                                                 
 dense_43 (Dense)            (None, 7)                 77        
                                                                 
Total params: 147 (588.00 Byte)
Trainable params: 147 (588.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Train the model

We train the model with a batch size of 128, ie 128 samples were passed through the network and the errors averaged before we adjusted the weights, then the next 128 samples were passed through. The network is trained for a total of 15 epochs (15 total passes through the whole training dataset).

The loss function in use here is categorical cross-entropy which is a common loss function used for classification problems. We are also using the ADAM optimizer here to control the overall learning rate without defining a constant learning rate.

In [77]:
# means after x pieces of data are forward passed it will average the errors, then do a backpropogation...it goes faster, and any odd data will be averaged out
batch_size = 1 # we're only using 1 because our dataset is very small
epochs = 15

# ! accuracy was never above 50%
# def one_hot(array):
#     # unique makes sure repeated values are treated as unique separate values
#     # inverse gives you the opposite
#     unique, inverse = np.unique(array, return_inverse=True)
#     # np.eye gives you an eye array that looks something like this [0, 0, 1, 0, 0]
#     onehot = np.eye(unique.shape[0])[inverse]
#     return onehot

# ! in jupyter notebook if you assign a variable back into its self be careful of when you run cells...values can get muddled up    
# y_train = one_hot(y_train)
# print(y_train.shape)
# print(y_train)

# ! accuracy was always around 50%....too little data? <- tried decreasing the num of hidden layers and accuracy increased to 60%
y_train = pd.Series(raw_labels)
print(y_train.loc[58])
y_train = pd.get_dummies(y_train)
print(y_train)

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Whitefish
     Bream  Parkki  Perch   Pike  Roach  Smelt  Whitefish
0     True   False  False  False  False  False      False
1     True   False  False  False  False  False      False
2     True   False  False  False  False  False      False
3     True   False  False  False  False  False      False
4     True   False  False  False  False  False      False
..     ...     ...    ...    ...    ...    ...        ...
154  False   False  False  False  False   True      False
155  False   False  False  False  False   True      False
156  False   False  False  False  False   True      False
157  False   False  False  False  False   True      False
158  False   False  False  False  False   True      False

[159 rows x 7 columns]


ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'pandas.core.frame.DataFrame'>]

# Evaluate the trained model

We expect a test accuracy of about 97% here.

In [ ]:
score = model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])